services:
    bbw.pmsearch.listener:
        class: bbw\pmsearch\event\main_listener
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@template'
            - '@bbw.pmsearch.search.helper'
        tags:
            - { name: event.listener }
    bbw.pmsearch.search.helper:
        class: bbw\pmsearch\helper
        arguments:
            - '@ext.manager'
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '@language'
            - '@dispatcher'
            - '%core.root_path%'
            - '%core.php_ext%'
    bbw.pmsearch.fulltext_native:
        class: bbw\pmadmin\search\pm_admin_fulltext_native
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '%core.table_prefix%'
            - '%core.root_path%'
            - '%core.php_ext%'
